version: '3.8'

services:
  db:
    build: .
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
  app:
    build: .
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/demo
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
